from os import getenv

TOKEN = getenv("TELEGRAM_TOKEN")
CHAT_ID = getenv("HEALTH_CHECK_CHAT_ID")

WEB_SERVER_HOST = "127.0.0.1"
WEB_SERVER_PORT = 8082
WEBHOOK_PATH = "/"
WEBHOOK_SECRET = "my-secret"
BASE_WEBHOOK_URL = "https://55fe-195-238-110-150.ngrok.io"