
name: Telebot

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
#    env:
#      DISPATCH: ${{ secrets.DISPATCH }}
#      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
#      HEALTH_CHECK_CHAT_ID: ${{ secrets.HEALTH_CHECK_CHAT_ID }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

#    - name: Run Bot
#      run: |
#        python executor/starting.py
